---
title: "Power Assets ATC Uganda Coordinates"
author: "Allan Kavuma"
date: "5 December 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, echo=FALSE, message=FALSE, warning=FALSE}
## Load libraries to read, manipulate and plot the data
library(xlsx) ## For reading excel file
library(dplyr) ## For data manipulation
library(leaflet)  ## For plotting coordinates on the graph
```

```{r readData, echo=FALSE, message=FALSE, warning=FALSE}
## Read the data
assetsData <- read.xlsx("Power - Assets - ATC Uganda Codinates.xlsx", sheetName = "data")
```

```{r dataExploration, echo=FALSE, message=FALSE, warning=FALSE,eval=FALSE}
str(assetsData)
table(is.na(assetsData$Latitude))
table(is.na(assetsData$Longitude))
table(is.na(assetsData$Site.Name))
colnames(assetsData)
```

```{r dataManipulation, echo=FALSE, message=FALSE, warning=FALSE}
## Change Site.Name field to character
assetsData$Site.Name <- as.character(assetsData$Site.Name)
```

```{r plotMap, echo=FALSE, message=FALSE, warning=FALSE}
## Plot map according to vendor
leaflet(assetsData) %>% addTiles() %>% addMarkers(
        lat = assetsData$Latitude,
        lng = assetsData$Longitude,
        popup = assetsData$Site.Name,
        clusterOptions = markerClusterOptions()
)
```